import type { AnggotaDirektoriItem, UnclaimedMemberItem, KlaimAkunItem } from '@/lib/types/membership';
import type { CalonSiswaItem } from '@/lib/types/registration';
import type { UserRoleRecord } from '@/lib/auth/types';

export interface MemberWithRolesItem {
  id: string;
  nama: string;
  status_keanggotaan: string;
  nia: string | null;
  jurusan: string | null;
  is_admin: boolean;
  angkatan?: {
    nomor_angkatan: number;
    nama_angkatan: string | null;
  } | null;
  roles: UserRoleRecord[];
}

export const MOCK_ANGGOTA: AnggotaDirektoriItem[] = [
  {
    id: 'mock-1',
    nama: 'Rian Pratama Putra',
    angkatan_id: 'angkatan-28',
    nomor_angkatan: 28,
    nama_angkatan: 'Tapak Rimba',
    status_keanggotaan: 'anggota_biasa',
    nia: 'GW.28.192.AB',
    foto_profil: null,
    jurusan: 'Pendidikan Geografi',
  },
  {
    id: 'mock-2',
    nama: 'Nabila Azzahra',
    angkatan_id: 'angkatan-29',
    nomor_angkatan: 29,
    nama_angkatan: 'Kabut Lembah',
    status_keanggotaan: 'anggota_biasa',
    nia: 'GW.29.205.AB',
    foto_profil: null,
    jurusan: 'Pendidikan Biologi',
  },
  {
    id: 'mock-3',
    nama: 'Fajar Nugraha',
    angkatan_id: 'angkatan-30',
    nomor_angkatan: 30,
    nama_angkatan: 'Elang Merbabu',
    status_keanggotaan: 'anggota_muda',
    nia: null,
    foto_profil: null,
    jurusan: 'Pendidikan Kepelatihan Olahraga',
  },
  {
    id: 'mock-4',
    nama: 'Dimas Ardiansyah',
    angkatan_id: 'angkatan-31',
    nomor_angkatan: 31,
    nama_angkatan: 'Cakrawala Sunda',
    status_keanggotaan: 'medan_operasi',
    nia: null,
    foto_profil: null,
    jurusan: 'Pendidikan Geografi',
  },
  {
    id: 'mock-5',
    nama: 'Siti Sarah Rahmawati',
    angkatan_id: 'angkatan-31',
    nomor_angkatan: 31,
    nama_angkatan: 'Cakrawala Sunda',
    status_keanggotaan: 'siswa',
    nia: null,
    foto_profil: null,
    jurusan: 'Pendidikan Seni Rupa',
  },
  {
    id: 'mock-6',
    nama: 'Ilham Kusuma Jaya',
    angkatan_id: 'angkatan-26',
    nomor_angkatan: 26,
    nama_angkatan: 'Badai Puncak',
    status_keanggotaan: 'anggota_luar_biasa',
    nia: 'GW.26.175.AB',
    foto_profil: null,
    jurusan: 'Pendidikan Teknik Mesin',
  },
  {
    id: 'mock-7',
    nama: 'Aditya Pratama',
    angkatan_id: 'angkatan-32',
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    status_keanggotaan: 'calon_siswa',
    nia: null,
    foto_profil: null,
    jurusan: 'Ilmu Komputer',
  },
  {
    id: 'mock-8',
    nama: 'Prof. Dr. Ir. Hendra Gunawan',
    angkatan_id: null,
    nomor_angkatan: null,
    nama_angkatan: null,
    status_keanggotaan: 'anggota_kehormatan',
    nia: 'GW.HON.003',
    foto_profil: null,
    jurusan: 'FPTI UPI',
  },
];

export const MOCK_CALON_SISWA_LIST: CalonSiswaItem[] = [
  {
    id: 'cs-mock-1',
    auth_user_id: 'user-auth-1',
    nama: 'Aditya Pratama Ramadhan',
    email: 'aditya.pratama@gmail.com',
    nim: '2301892',
    jurusan: 'Pendidikan Geografi',
    no_hp: '081234567891',
    alamat: 'Jl. Gegerkalong Tonggoh No. 15 Bandung',
    jenis_kelamin: 'L',
    tempat_lahir: 'Bandung',
    tanggal_lahir: '2004-05-12',
    file_persetujuan_ortu: '/uploads/persetujuan_aditya.pdf',
    status_keanggotaan: 'calon_siswa',
    created_at: '2025-08-10T10:30:00Z',
    angkatan: { id: 'angkatan-32', nomor_angkatan: 32, nama_angkatan: 'Giri Wardhana' },
    periode_pendaftaran: { id: 'periode-aktif-32', catatan: 'Penerimaan Angkatan 32', status: 'buka' },
    tes_kesehatan_awal: {
      id: 'tes-1',
      anggota_id: 'cs-mock-1',
      jenis: 'awal',
      file_surat_dokter: '/uploads/surat_dokter_aditya.pdf',
      catatan_panitia: 'Fisik prima, tekanan darah normal 120/80, tidak ada riwayat asma akut.',
      tanggal: '2025-08-15',
      created_at: '2025-08-15T00:00:00Z',
    },
    keputusan_tahap: {
      id: 'rw-1',
      tahap: 'calon_siswa',
      status: 'dalam_proses',
      catatan: 'Menunggu peninjauan akhir Ketua Medan Operasi.',
      approver_nama: null,
      tanggal: '2025-08-10',
    },
  },
  {
    id: 'cs-mock-2',
    auth_user_id: 'user-auth-2',
    nama: 'Alya Putri Salsabila',
    email: 'alya.putri@gmail.com',
    nim: '2304521',
    jurusan: 'Pendidikan Biologi',
    no_hp: '082198765431',
    alamat: 'Jl. Dr. Setiabudhi No. 198 Bandung',
    jenis_kelamin: 'P',
    tempat_lahir: 'Cimahi',
    tanggal_lahir: '2005-02-18',
    file_persetujuan_ortu: '/uploads/persetujuan_alya.pdf',
    status_keanggotaan: 'siswa',
    created_at: '2025-08-05T09:15:00Z',
    angkatan: { id: 'angkatan-32', nomor_angkatan: 32, nama_angkatan: 'Giri Wardhana' },
    periode_pendaftaran: { id: 'periode-aktif-32', catatan: 'Penerimaan Angkatan 32', status: 'buka' },
    tes_kesehatan_awal: {
      id: 'tes-2',
      anggota_id: 'cs-mock-2',
      jenis: 'awal',
      file_surat_dokter: '/uploads/surat_dokter_alya.pdf',
      catatan_panitia: 'Kondisi fisik stabil, tes kebugaran 12 menit memenuhi standar.',
      tanggal: '2025-08-12',
      created_at: '2025-08-12T00:00:00Z',
    },
    keputusan_tahap: {
      id: 'rw-2',
      tahap: 'calon_siswa',
      status: 'lolos',
      catatan: 'Memenuhi seluruh kriteria seleksi fisik & kelengkapan berkas resmi.',
      approver_nama: 'Ketua Medan Operasi',
      tanggal: '2025-08-20',
    },
  },
  {
    id: 'cs-mock-3',
    auth_user_id: 'user-auth-3',
    nama: 'Rizwan Maulana',
    email: 'rizwan.m@gmail.com',
    nim: '2209182',
    jurusan: 'Pendidikan Teknik Mesin',
    no_hp: '085712349999',
    alamat: 'Jl. Sariwangi Asri No. 4 Bandung Barat',
    jenis_kelamin: 'L',
    tempat_lahir: 'Sukabumi',
    tanggal_lahir: '2003-11-04',
    file_persetujuan_ortu: null,
    status_keanggotaan: 'calon_siswa',
    created_at: '2025-08-14T14:20:00Z',
    angkatan: { id: 'angkatan-32', nomor_angkatan: 32, nama_angkatan: 'Giri Wardhana' },
    periode_pendaftaran: { id: 'periode-aktif-32', catatan: 'Penerimaan Angkatan 32', status: 'buka' },
    tes_kesehatan_awal: null,
    keputusan_tahap: {
      id: 'rw-3',
      tahap: 'calon_siswa',
      status: 'dalam_proses',
      catatan: 'Menunggu kelengkapan surat persetujuan ortu & surat dokter.',
      approver_nama: null,
      tanggal: '2025-08-14',
    },
  },
];

export const MOCK_UNCLAIMED: UnclaimedMemberItem[] = [
  {
    id: 'unclaimed-1',
    nama: 'Bambang Trihatmodjo',
    nomor_angkatan: 27,
    nama_angkatan: 'Pijar Lembah',
    status_keanggotaan: 'anggota_biasa',
    jurusan: 'Pendidikan Geografi',
  },
  {
    id: 'unclaimed-2',
    nama: 'Bayu Wicaksono',
    nomor_angkatan: 28,
    nama_angkatan: 'Tapak Rimba',
    status_keanggotaan: 'anggota_biasa',
    jurusan: 'Pendidikan Bahasa Inggris',
  },
  {
    id: 'unclaimed-3',
    nama: 'Annisa Nurul Hidayah',
    nomor_angkatan: 29,
    nama_angkatan: 'Kabut Lembah',
    status_keanggotaan: 'anggota_muda',
    jurusan: 'Pendidikan Biologi',
  },
  {
    id: 'unclaimed-4',
    nama: 'Rizky Kurniawan',
    nomor_angkatan: 30,
    nama_angkatan: 'Elang Merbabu',
    status_keanggotaan: 'anggota_muda',
    jurusan: 'Ilmu Keolahragaan',
  },
];

export const MOCK_PENDING_CLAIMS: KlaimAkunItem[] = [
  {
    id: 'claim-mock-1',
    auth_user_id: 'auth-user-123',
    anggota_id: 'unclaimed-1',
    status: 'menunggu',
    catatan_admin: 'Catatan pemohon: Saya Bambang Trihatmodjo angkatan 27, NIM 1904123 Pend. Geografi. Ingin menghubungkan akun Google ini.',
    diproses_oleh: null,
    diproses_pada: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    user_email: 'bambang.tri@gmail.com',
    anggota: {
      id: 'unclaimed-1',
      nama: 'Bambang Trihatmodjo',
      status_keanggotaan: 'anggota_biasa',
      nia: 'GW.27.180.AB',
      jurusan: 'Pendidikan Geografi',
      angkatan: {
        nomor_angkatan: 27,
        nama_angkatan: 'Pijar Lembah',
      },
    },
  },
  {
    id: 'claim-mock-2',
    auth_user_id: 'auth-user-456',
    anggota_id: 'unclaimed-2',
    status: 'menunggu',
    catatan_admin: 'Catatan pemohon: Bayu Wicaksono, Tapak Rimba (Angkatan 28). Login via akun Google institusi.',
    diproses_oleh: null,
    diproses_pada: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    user_email: 'bayu.wicaksono@upi.edu',
    anggota: {
      id: 'unclaimed-2',
      nama: 'Bayu Wicaksono',
      status_keanggotaan: 'anggota_biasa',
      nia: 'GW.28.195.AB',
      jurusan: 'Pendidikan Bahasa Inggris',
      angkatan: {
        nomor_angkatan: 28,
        nama_angkatan: 'Tapak Rimba',
      },
    },
  },
];

export const MOCK_MEMBERS_WITH_ROLES: MemberWithRolesItem[] = [
  {
    id: 'mock-1',
    nama: 'Rian Pratama Putra',
    status_keanggotaan: 'anggota_biasa',
    nia: 'GW.28.192.AB',
    jurusan: 'Pendidikan Geografi',
    is_admin: true,
    angkatan: { nomor_angkatan: 28, nama_angkatan: 'Tapak Rimba' },
    roles: [
      {
        id: 'role-1',
        anggota_id: 'mock-1',
        role: 'admin',
        periode_mulai: '2024-01-01',
        periode_selesai: null,
        is_active: true,
        created_at: '2024-01-01T00:00:00Z',
      },
      {
        id: 'role-2',
        anggota_id: 'mock-1',
        role: 'ketua_dp',
        periode_mulai: '2024-01-01',
        periode_selesai: '2025-01-01',
        is_active: true,
        created_at: '2024-01-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'mock-2',
    nama: 'Nabila Azzahra',
    status_keanggotaan: 'anggota_biasa',
    nia: 'GW.29.205.AB',
    jurusan: 'Pendidikan Biologi',
    is_admin: false,
    angkatan: { nomor_angkatan: 29, nama_angkatan: 'Kabut Lembah' },
    roles: [
      {
        id: 'role-3',
        anggota_id: 'mock-2',
        role: 'ketua_organisasi',
        periode_mulai: '2024-06-01',
        periode_selesai: '2025-06-01',
        is_active: true,
        created_at: '2024-06-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'mock-3',
    nama: 'Fajar Nugraha',
    status_keanggotaan: 'anggota_muda',
    nia: null,
    jurusan: 'PKO',
    is_admin: false,
    angkatan: { nomor_angkatan: 30, nama_angkatan: 'Elang Merbabu' },
    roles: [
      {
        id: 'role-4',
        anggota_id: 'mock-3',
        role: 'panitia',
        periode_mulai: '2024-08-01',
        periode_selesai: '2025-02-01',
        is_active: true,
        created_at: '2024-08-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'mock-4',
    nama: 'Dimas Ardiansyah',
    status_keanggotaan: 'medan_operasi',
    nia: null,
    jurusan: 'Pendidikan Geografi',
    is_admin: false,
    angkatan: { nomor_angkatan: 31, nama_angkatan: 'Cakrawala Sunda' },
    roles: [],
  },
];

