import type {
  JabatanOrganisasiItem,
  DewanPenasehatItem,
  CandidateALBItem,
  SertifikatItem,
} from '@/lib/types/governance';

export const MOCK_JABATAN: JabatanOrganisasiItem[] = [
  {
    id: 'jab-1',
    anggota_id: 'am-1',
    anggota_nama: 'Alya Putri Salsabila',
    anggota_nim: '2304521',
    anggota_nia: 'GW.32.235.GW',
    foto_profil: null,
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    status_keanggotaan: 'anggota_biasa',
    jabatan: 'Ketua Umum Organisasi',
    divisi: 'Badan Pengurus Harian (BPH)',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Terpilih secara aklamasi pada Musyawarah Anggota 2024.',
    is_active: true,
  },
  {
    id: 'jab-2',
    anggota_id: 'am-2',
    anggota_nama: 'Aditya Pratama Ramadhan',
    anggota_nim: '2304522',
    anggota_nia: 'GW.32.236.GW',
    foto_profil: null,
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    status_keanggotaan: 'anggota_biasa',
    jabatan: 'Wakil Ketua Organisasi',
    divisi: 'Badan Pengurus Harian (BPH)',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Koordinator operasional dan divisi teknik kepetualangan.',
    is_active: true,
  },
  {
    id: 'jab-3',
    anggota_id: 'am-3',
    anggota_nama: 'Farhan Dwi Cahyo',
    anggota_nim: '2304523',
    anggota_nia: 'GW.32.237.GW',
    foto_profil: null,
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    status_keanggotaan: 'anggota_biasa',
    jabatan: 'Sekretaris Umum',
    divisi: 'Kesekretariatan & Administrasi',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Penanggung jawab arsip, persuratan, dan basis data keanggotaan.',
    is_active: true,
  },
  {
    id: 'jab-4',
    anggota_id: 'am-4',
    anggota_nama: 'Nabila Zahra Arifin',
    anggota_nim: '2304524',
    anggota_nia: 'GW.32.238.GW',
    foto_profil: null,
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    status_keanggotaan: 'anggota_biasa',
    jabatan: 'Bendahara Umum',
    divisi: 'Keuangan & Kewirausahaan',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Pengelola buku kas organisasi dan iuran wajib.',
    is_active: true,
  },
  {
    id: 'jab-5',
    anggota_id: 'am-5',
    anggota_nama: 'Reza Mahendra Kusuma',
    anggota_nim: '2304525',
    anggota_nia: 'GW.32.239.GW',
    foto_profil: null,
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    status_keanggotaan: 'anggota_biasa',
    jabatan: 'Ketua Divisi Gunung Hutan & Navigasi',
    divisi: 'Divisi Operasional Lapangan',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Instruktur kurikulum navigasi dan survival rimba.',
    is_active: true,
  },
  {
    id: 'jab-6',
    anggota_id: 'am-6',
    anggota_nama: 'Bima Satria Yudha',
    anggota_nim: '2304526',
    anggota_nia: 'GW.32.240.GW',
    foto_profil: null,
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    status_keanggotaan: 'anggota_biasa',
    jabatan: 'Komandan Latihan (Danlat) Medan Operasi',
    divisi: 'Divisi Kaderisasi',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Penanggung jawab lapangan diklat calon generasi penerus.',
    is_active: true,
  },
];

export const MOCK_DEWAN_PENASEHAT: DewanPenasehatItem[] = [
  {
    id: 'dpn-1',
    anggota_id: 'alb-1',
    anggota_nama: 'Ir. Hendra Gunawan, S.T., M.T.',
    anggota_nim: '0901244',
    anggota_nia: 'GW.18.092.RH',
    foto_profil: null,
    nomor_angkatan: 18,
    nama_angkatan: 'Rimba Halimun',
    status_keanggotaan: 'anggota_luar_biasa',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Penasehat Bidang Ekspedisi Internasional & Kemitraan Alumni.',
  },
  {
    id: 'dpn-2',
    anggota_id: 'alb-2',
    anggota_nama: 'Dra. Maya Kartika Dewi, M.Pd.',
    anggota_nim: '1002381',
    anggota_nia: 'GW.19.105.BC',
    foto_profil: null,
    nomor_angkatan: 19,
    nama_angkatan: 'Bumi Cendekia',
    status_keanggotaan: 'anggota_luar_biasa',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Penasehat Bidang Pendidikan Konservasi & Hubungan Rektorat UPI.',
  },
  {
    id: 'dpn-3',
    anggota_id: 'alb-3',
    anggota_nama: 'Dr. Ahmad Fauzi, S.Si.',
    anggota_nim: '1203492',
    anggota_nia: 'GW.21.134.SP',
    foto_profil: null,
    nomor_angkatan: 21,
    nama_angkatan: 'Singa Prawira',
    status_keanggotaan: 'anggota_luar_biasa',
    periode_mulai: '2024-01-01',
    periode_selesai: '2025-12-31',
    catatan: 'Penasehat Manajemen Risiko Ekspedisi & Litbang Kebencanaan.',
  },
];

export const MOCK_CANDIDATES_ALB: CandidateALBItem[] = [
  {
    id: 'am-1',
    nama: 'Alya Putri Salsabila',
    nim: '2304521',
    nia: 'GW.32.235.GW',
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    jurusan: 'Pendidikan Teknik Mesin',
    status_keanggotaan: 'anggota_biasa',
    tanggal_berubah_status: '2025-12-20',
  },
  {
    id: 'am-2',
    nama: 'Aditya Pratama Ramadhan',
    nim: '2304522',
    nia: 'GW.32.236.GW',
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    jurusan: 'Pendidikan Teknik Elektro',
    status_keanggotaan: 'anggota_biasa',
    tanggal_berubah_status: '2025-12-20',
  },
  {
    id: 'am-3',
    nama: 'Farhan Dwi Cahyo',
    nim: '2304523',
    nia: 'GW.32.237.GW',
    nomor_angkatan: 32,
    nama_angkatan: 'Giri Wardhana',
    jurusan: 'Pendidikan Teknik Sipil',
    status_keanggotaan: 'anggota_biasa',
    tanggal_berubah_status: '2025-12-20',
  },
];

export const MOCK_ALL_ALB: CandidateALBItem[] = [
  {
    id: 'alb-1',
    nama: 'Ir. Hendra Gunawan, S.T., M.T.',
    nim: '0901244',
    nia: 'GW.18.092.RH',
    nomor_angkatan: 18,
    nama_angkatan: 'Rimba Halimun',
    jurusan: 'Teknik Elektro',
    status_keanggotaan: 'anggota_luar_biasa',
    tanggal_berubah_status: '2014-08-15',
  },
  {
    id: 'alb-2',
    nama: 'Dra. Maya Kartika Dewi, M.Pd.',
    nim: '1002381',
    nia: 'GW.19.105.BC',
    nomor_angkatan: 19,
    nama_angkatan: 'Bumi Cendekia',
    jurusan: 'Pendidikan Biologi',
    status_keanggotaan: 'anggota_luar_biasa',
    tanggal_berubah_status: '2015-09-20',
  },
  {
    id: 'alb-3',
    nama: 'Dr. Ahmad Fauzi, S.Si.',
    nim: '1203492',
    nia: 'GW.21.134.SP',
    nomor_angkatan: 21,
    nama_angkatan: 'Singa Prawira',
    jurusan: 'Pendidikan Geografi',
    status_keanggotaan: 'anggota_luar_biasa',
    tanggal_berubah_status: '2017-06-10',
  },
];

export const MOCK_SERTIFIKAT: SertifikatItem[] = [
  {
    id: 'sert-1',
    anggota_id: 'am-1',
    anggota_nama: 'Alya Putri Salsabila',
    anggota_nia: 'GW.32.235.GW',
    jenis: 'Kelulusan PPNIA & Pengukuhan NIA',
    judul: 'Piagam Pengukuhan Anggota Biasa & Kelulusan PPNIA Angkatan 32',
    nomor_sertifikat: '042/SK-NIA/GW-FPTI/XII/2025',
    tanggal_terbit: '2025-12-20',
    file: 'https://storage.googleapis.com/gandawesi-assets/sertifikat/ppnia-32-042.pdf',
    deskripsi: 'Dinyatakan telah menuntaskan seluruh 4 pilar pembinaan, seminar LPJ, dan ekspedisi mandiri.',
  },
  {
    id: 'sert-2',
    anggota_id: 'am-1',
    anggota_nama: 'Alya Putri Salsabila',
    anggota_nia: 'GW.32.235.GW',
    jenis: 'Pelantikan Medan Operasi',
    judul: 'Sertifikat Kelulusan Medan Operasi & Pelantikan Anggota Muda Giri Wardhana',
    nomor_sertifikat: '018/MO-LULUS/GW-FPTI/IV/2025',
    tanggal_terbit: '2025-04-12',
    file: 'https://storage.googleapis.com/gandawesi-assets/sertifikat/mo-32-018.pdf',
    deskripsi: 'Lolos uji kelayakan fisik dan ketahanan mental 12 hari di Gunung Ciremai.',
  },
  {
    id: 'sert-3',
    anggota_id: 'am-1',
    anggota_nama: 'Alya Putri Salsabila',
    anggota_nia: 'GW.32.235.GW',
    jenis: 'Pendidikan & Latihan Dasar (Siswa)',
    judul: 'Piagam Kelulusan Tahap Siswa & Post-Test Materi Kepecintaalaman',
    nomor_sertifikat: '005/DIKLAT/GW-FPTI/II/2025',
    tanggal_terbit: '2025-02-28',
    file: 'https://storage.googleapis.com/gandawesi-assets/sertifikat/siswa-32-005.pdf',
    deskripsi: 'Menyelesaikan 24 sesi bina jasmani dan post-test navigasi darat.',
  },
];
